### ISSUE TITLE
Quartz cron expression

### ISSUE THREAD

**Issue by angeloscaldaferri** [shawnchin/jquery-cron#7]
Hi Shawn Chin,
congratulations for your job. Have you already developed a Quartz cron expression version?
Otherwise think of developing it?
I'd really need it but I could not find anything on the web.

Thanks

**Comment by jerry27syd** [comment]
Hi shawnchin,
It would be good to implment this for quartz

**Comment by felixruponen** [comment]
Hi 

I've forked the project and implemented the same functionality but with quartz format instead of regular cron. Feel free to check it out

https://github.com/felixruponen/jquery-cron

**Comment by angeloscaldaferri** [comment]
Tanks felixruponen!!

**Comment by aaangga** [comment]
Hi @felixruponen, it seems your code doesn't work

I've checked index.html for both yours and @shawnchin's 
On Introduction section, it's should be two demos, but the demos on your index.html doesn't work.

**Comment by aaangga** [comment]
Ooops, my bad. Sorry @felixruponen, your code work really well.
I shouldn't put initial cron at first.
Thank you
